// Actions Register
export const GET_DATA_REGISTER="GET_DATA_REGISTER";
export const DATA_REGISTER="DATA_REGISTER";
export const ERRO_DATA_REGISTER="ERRO_DATA_REGISTER";
// Actions Confirm Email
export const GET_DATA_CONFIRMEMAIL="GET_DATA_CONFIRMEMAIL";
export const DATA_CONFIRMEMAIL="DATA_CONFIRMEMAIL";
export const ERRO_CONFIRMEMAIL="ERRO_CONFIRMEMAI";
export const FAILD_CONFIRM="FAILD_CONFIRM";

// Actions Resend Code
export const GET_DATA_RESENDCODE="GET_DATA_RESENDCODE";
export const DATA_RESENDCODE="DATA_RESENDCODE";
export const ERRO_RESENDCODE="ERRO_RESENDCODE";
// Actions  Complete Register
export const GET_DATA_COMPLETE_REGISTER="GET_DATA_COMPLETE_REGISTER";
export const DATA_COMPLETE_REGISTER="DATA_COMPLETE_REGISTER";
export const ERRO_COMPLETE_REGISTER="RRO_COMPLETE_REGISTER";
// Actions  Login
export const GET_DATA_LOGIN="GET_DATA_LOGIN";
export const DATA_LOGIN="DATA_LOGIN";
export const ERRO_LOGIN="ERRO_LOGIN";
// Actions  forget password
export const GET_DATA_FORGET_PASSWORD="GET_DATA_FORGET_PASSWORD";
export const DATA_FORGET_PASSWORD="DATA_FORGET_PASSWORD";
export const ERRO_FORGET_PASSWORD="ERRO_FORGET_PASSWORD";
// Actions  Reset password
export const GET_DATA_RESET_PASSWORD="GET_DATA_RESET_PASSWORD";
export const DATA_RESET_PASSWORD="DATA_RESET_PASSWORD";
export const ERRO_RESET_PASSWORD="ERRO_RESET_PASSWORD";
//Actions get Employees 
export const GET_DATA_EMPLOYEE="GET_DATA_EMPLOYEE";
export const DATA_EMPLOYEE="DATA_EMPLOYEE";
export const ERRO_EMPLOYEE="ERRO_EMPLOYEE";
//Actions Add Employees 
export const GET_ADD_EMPLOYEE="GET_ADD_EMPLOYEE";
export const DATA_ADD_EMPLOYEE="DATA_ADD_EMPLOYE";
export const ERRO_ADD_EMPLOYEE="ERRO_ADD_EMPLOYEE";
//Actions Update Employees 
export const GET_UPDATE_EMPLOYEE="GET_UPDATE_EMPLOYEE";
export const DATA_UPDATE_EMPLOYEE="DATA_UPDATE_EMPLOYE";
export const ERRO_UPDATE_EMPLOYEE="ERRO_UPDATE_EMPLOYEE";
//Actions Delete Employees 
export const GET_DELETE_EMPLOYEE="GET_DELETE_EMPLOYEE";
export const DATA_DELETE_EMPLOYEE="DATA_DELETE_EMPLOYEE";
export const ERRO_DELETE_EMPLOYEE="ERRO_DELETE_EMPLOYEE";
//Actions Get Mission 
export const GET_DATA_MISSION="GET_DATA_MISSION";
export const DATA_MISSION=" DATA_MISSION";
export const ERRO_MISSION="ERRO_MISSION";
//Actions  Cretae Mission
export const CREATE_DATA_MISSION="REATE_DATA_MISSION";
export const DATA_CREATE_MISSION=" DATA_CREATE_MISSION";
export const ERRO_CREATE_MISSION="ERRO_CREATE_MISSION"
//Actions  Update Mission
export const UPDATE_DATA_MISSION="UpATE_DATA_MISSION";
export const UPDATE_MISSION=" UPDATE_MISSION";
export const ERRO_UPDATE_MISSION="ERRO_UPDATE_MISSION"
//Actions  Delete Mission
export const DELETE_DATA_MISSION="DELETE_DATA_MISSION";
export const DELETE_MISSION="DELETE_MISSION";
export const ERRO_DELETE_MISSION=" ERRO_DELETE_MISSION"
//Actions  Get Milistone
export const GET_DATA_MILISTONE="GET_DATA_MILISTONE";
export const DATA_MILISTONE="DATA_MILISTONE";
export const ERRO_MILISTONE=" ERRO_MILISTON"
//Actions  Cretae Milestone
export const CREATE_DATA_MILESTONE="CREATE_DATA_MILESTONE";
export const DATA_CREATE_MILESTONE=" DATA_CREATE_MILESTONE";
export const ERRO_CREATE_MILESTONE="ERRO_CREATE_MILESTONE"
//Actions  Update Milestone
export const UPDATE_DATA_MILESTONE="UPDATE_DATA_MILESTONE";
export const UPDATE_MILESTONE=" DATA_UPDATE_MILESTONE";
export const ERRO_UPDATE_MILESTONE="ERRO_UPDATE_MILESTONE"
//Actions  Update Milestone
export const DELETE_DATA_MILESTONE="DELETE_DATA_MILESTONE";
export const DELETE_MILESTONE=" DELETE_MILESTONE";
export const ERRO_DELETE_MILESTONE="ERRO_DELETE_MILESTONE"

